name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - name: Obtendo o código
      uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PWD}}
    - name: Construção da imagem Docker worker
      uses: docker/build-push-action@v5.0.0
      with: 
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          fabricioveronez/simulador-do-caos:v1
          fabricioveronez/simulador-do-caos:latest  
          kubedevio/simulador-do-caos:v1
          kubedevio/simulador-do-caos:latest  
