services:
  web:
    image: fabricioveronez/simulador-do-caos:v1
    ports:
      - "8080:3000"
    restart: always
    healthcheck:
      test: ["executable", "arg"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    cpuset: 0.5
    memswap: 1g
    deploy:  
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
        #reservations:
         # cpus: "0.5"
         # memory: 1G